import {
  icoApp,
  icoWeb,
  icoCMS,
  icoUIUX,
  imgWTS,
  imgRTT,
  imgPAO,
  imgYM,
  imgTAP,
  imgFURAMA,
  imgHBO,
  imgFWD,
  imgKIWI,
  imgISE,
  imgECO
} from "./images";

const workCategoriesData = {
  all: "All",
  food: "Food & Beverage",
  media: "Media",
  transport: "Transport & Logistics",
  banking: "Banking & Finance",
  lifestyle: "Lifestyle",
  incube: "Co-incubation",
  health: "Healthcare",
  retail: "Retail & Entertainment",
  telco: "Telco",
  others: "Others",
  startup: "Start-ups",
};

const workLegendsData = [
  {
    name: "App",
    img: icoApp,
  },
  {
    name: "Web",
    img: icoWeb,
  },
  {
    name: "CMS",
    img: icoCMS,
  },
  {
    name: "UIUX",
    img: icoUIUX,
  },
];

const workFiltersData = [
  {
    name: "OCBC Pay Anyone",
    category: "Transport & Logistics",
    ctgIds: ["transport"],
    platforms: [icoApp, icoCMS],
    img: imgPAO,
    size: "w-50",
    isShow: true,
  },
  {
    name: "Ecolab",
    category: "Others",
    ctgIds: ["others"],
    platforms: [icoApp, icoCMS, icoUIUX],
    img: imgECO,
    size: "w-25",
    isShow: true,
    url: "/work-detail",
  },
  {
    name: "KIWI Auto Marketplace",
    category: "Others, Start-ups",
    ctgIds: ["others", "startup"],
    platforms: [icoApp, icoWeb, icoCMS, icoUIUX],
    img: imgKIWI,
    size: "w-25",
    isShow: true,
    url: "/work-detail",
  },
  {
    name: "Furama Hotels",
    category: "Lifestyle",
    ctgIds: ["lifestyle"],
    platforms: [icoApp, icoCMS],
    img: imgFURAMA,
    size: "w-25",
    isShow: true,
  },
  {
    name: "Woodlands Transport",
    category: "Transport & Logistics",
    ctgIds: ["transport"],
    platforms: [icoApp, icoWeb, icoCMS, icoUIUX],
    img: imgWTS,
    size: "w-25",
    isShow: true,
  },
  {
    name: "Ready to Travel (SATS)",
    category: "Lifestyle, Retail & Entertainment, Start-ups",
    ctgIds: ["lifestyle", "retail", "startup"],
    platforms: [icoApp, icoWeb, icoCMS, icoUIUX],
    img: imgRTT,
    size: "w-50",
    isShow: true,
  },
  {
    name: "Yoga Movement",
    category: "Lifestyle",
    ctgIds: ["lifestyle"],
    platforms: [icoApp, icoWeb, icoCMS, icoUIUX],
    img: imgYM,
    size: "w-50",
    isShow: true,
  },
  {
    name: "HBO Go",
    category: "Retail & Entertainment",
    ctgIds: ["retail"],
    platforms: [icoApp, icoWeb, icoCMS, icoUIUX],
    img: imgHBO,
    size: "w-50",
    isShow: true,
  },
  {
    name: "TAP Ride Hailing",
    category: "Transport & Logistics",
    ctgIds: ["transport"],
    platforms: [icoApp],
    img: imgTAP,
    size: "w-25",
    isShow: true,
  },

  {
    name: "FWD Insurance",
    category: "Lifestyle",
    ctgIds: ["lifestyle"],
    platforms: [icoApp, icoCMS, icoUIUX],
    img: imgFWD,
    size: "w-50",
    isShow: true,
  },
  {
    name: "Isetan",
    category: "Retail & Entertainment",
    ctgIds: ["retail"],
    platforms: [icoApp, icoCMS, icoUIUX],
    img: imgISE,
    size: "w-25",
    isShow: true,
  },
];

export { workCategoriesData, workLegendsData, workFiltersData };
